### ISSUE TITLE
Mod is Incompatible with Quilt 1.19.3

### ISSUE THREAD

**Issue by KiloPetraGames** [SzczurekYT/Effective#1]
@SzczurekYT Hello!

This version of the mod doesn't seem to be compatible with 1.19.3. Is there some way to modify it?

Loaded with:
quilt-loader-0.19.2-1.19.3
[1.19.3] QFAPI 5.0.0-beta.9 and QSL 4.0.0-beta.13

Here's the crash report:
[crash-2023-07-27_18.21.50.4073-quilt_loader.txt](https://github.com/SzczurekYT/Effective/files/12195059/crash-2023-07-27_18.21.50.4073-quilt_loader.txt)

**Comment by SzczurekYT** [comment]
> @SzczurekYT Hello!
> 
> This version of the mod doesn't seem to be compatible with 1.19.3. Is there some way to modify it?
> 
> Loaded with: quilt-loader-0.19.2-1.19.3 [1.19.3] QFAPI 5.0.0-beta.9 and QSL 4.0.0-beta.13
> 
> Here's the crash report: [crash-2023-07-27_18.21.50.4073-quilt_loader.txt](https://github.com/SzczurekYT/Effective/files/12195059/crash-2023-07-27_18.21.50.4073-quilt_loader.txt)
@KiloPetraGames 
Oh hello, sorry, I didn't saw the issue, I don't know how I missed it.
I checked the log and it's not something you can fix without changing the code.
I might do a backport, but I don't promise.

**Comment by KiloPetraGames** [comment]
> > @SzczurekYT Hello!
> > This version of the mod doesn't seem to be compatible with 1.19.3. Is there some way to modify it?
> > Loaded with: quilt-loader-0.19.2-1.19.3 [1.19.3] QFAPI 5.0.0-beta.9 and QSL 4.0.0-beta.13
> > Here's the crash report: [crash-2023-07-27_18.21.50.4073-quilt_loader.txt](https://github.com/SzczurekYT/Effective/files/12195059/crash-2023-07-27_18.21.50.4073-quilt_loader.txt)
> > @KiloPetraGames
> > Oh hello, sorry, I didn't saw the issue, I don't know how I missed it.
> > I checked the log and it's not something you can fix without changing the code.
> > I might do a backport, but I don't promise.

I understand. If you did backport it, that would be amazing! But if not, thank you so much for taking the time to look into this regardless!
